name: tapcounter_flutter
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  # Include any assets you want to bundle at runtime
  assets:
    - assets/icon.png

  module:
    androidX: true
    androidPackage: com.example.flutter_module_1
    iosBundleIdentifier: com.example.flutterModule1
